import AsyncStorage from '@react-native-async-storage/async-storage';
// `storybook.requires` is generated by `yarn storybook-generate`
// (bin: sb-rn-get-stories). It wires up every story + on-device addon.
import { view } from './storybook.requires';

const StorybookUIRoot = view.getStorybookUI({
  storage: {
    getItem: AsyncStorage.getItem,
    setItem: AsyncStorage.setItem,
  },
});

export default StorybookUIRoot;
